### ISSUE TITLE
Improve robustness

### ISSUE THREAD

**Issue by ADAAlchemist** [matthewrenze/rename-images#2]
Thanks for this script. I suggest small modifications to improve robustness and os compatibility:
Linux is case sensitive:
```
# Set list of valid file extensions
valid_extensions = [".jpg", ".JPG", ".jpeg", ".JPEG", ".png", ".PNG"]
```
Some jpg-files seem to have the date taken information in exif-key 306
```
    # Get the date taken from EXIF metadata
    # date_taken = image._getexif()[36867]
    exif = image._getexif()

    if 36867 in exif.keys():
        date_taken = exif[36867]
    elif 306 in exif.keys():
        date_taken = exif[306]
    else:
        print("date information not found from file: %s" % (file_name))
        continue
```

**Comment by 4x4Robots** [comment]
Thank you, @matthewrenze, for sharing the script and also @ADAAlchemist for the shared modifications, it saved me some probably frustrating minutes of searching!

**Comment by matthewrenze** [comment]
Thanks @ADAAlchemist and @4x4Robots! 

I incorporated your suggested changes to the script and updated the documentation.
